name: PSR12 code

on: [push, pull_request]

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Update composer.lock
        run: composer update

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Detecting PHP Code Standards Violations
        run: composer run-script phpcs
