name: Unit tests PHP 5.4,5.6

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php-versions: [5.4, 5.6]
    name: PHP ${{ matrix.php-versions }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: intl #optional
        ini-values: "post_max_size=256M" #optional
    
    - name: Check PHP Version
      run: php -v
    
    - name: Remove phpstan from composer
      run: sed -i "/\bphpstan\b/d" composer.json

    - name: Update composer.lock
      run: composer update --ignore-platform-reqs
      
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Run test suite
      run: composer run-script unittest
